def ingredients():
    ingredients = [
    "flour",
    "sugar",
    "butter",
    "eggs",
    "milk",
    "salt",
    "pepper",
    "vanilla extract",
    "baking powder",
    "baking soda",
    "chocolate chips",
    "cocoa powder",
    "honey",
    "maple syrup",
    "olive oil",
    "vegetable oil",
    "coconut oil",
    "soy sauce",
    "rice vinegar",
    "sesame oil",
    "garlic",
    "onion",
    "ginger",
    "cilantro",
    "parsley",
    "basil",
    "thyme",
    "rosemary",
    "oregano",
    "cumin",
    "coriander",
    "cayenne pepper",
    "paprika",
    "nutmeg",
    "cinnamon",
    "turmeric",
    "mustard seeds",
    "bay leaves",
    "cloves",
    "cardamom",
    "star anise",
    "tamarind",
    "black pepper",
    "white pepper",
    "red pepper flakes",
    "cane sugar",
    "brown sugar",
    "powdered sugar",
    "confectioners' sugar",
    "granulated sugar",
    "molasses",
    "cornstarch",
    "potato starch",
    "arrowroot",
    "xanthan gum",
    "cream cheese",
    "sour cream",
    "yogurt",
    "buttermilk",
    "heavy cream",
    "whipping cream",
    "evaporated milk",
    "condensed milk",
    "cream of tartar",
    "lemon juice",
    "lime juice",
    "orange juice",
    "apple cider vinegar",
    "red wine vinegar",
    "balsamic vinegar",
    "coconut milk",
    "almond milk",
    "cashew milk",
    "rice milk",
    "soy milk",
    "oats",
    "quinoa",
    "rice",
    "pasta",
    "barley",
    "bulgur",
    "couscous",
    "bread crumbs",
    "cornmeal",
    "walnuts",
    "almonds",
    "cashews",
    "peanuts",
    "hazelnuts",
    "pecans",
    "macadamia nuts",
    "pistachios",
    "sunflower seeds",
    "pumpkin seeds",
    "chia seeds",
    "flaxseeds",
    "poppy seeds",
    "sesame seeds",
    "dried cranberries",
    "raisins",
    "dates",
    "figs",
    "prunes",
    "apricots",
    "cherries",
    "blueberries",
    "strawberries",
    "raspberries",
    "blackberries",
    "bananas",
    "apples",
    "pears",
    "peaches",
    "plums",
    "kiwis",
    "mangoes",
    "pineapples",
    "avocados",
    "lemons",
    "limes",
    "oranges",
    "grapefruits",
    "watermelon",
    "cantaloupe",
    "honeydew melon",
    "coconut",
    "passion fruit",
    "dragon fruit",
    "pomegranate",
    "tomatoes",
    "cucumbers",
    "carrots",
    "celery",
    "bell peppers",
    "spinach",
    "kale",
    "lettuce",
    "arugula",
    "zucchini",
    "eggplant",
    "broccoli",
    "cauliflower",
    "mushrooms",
    "onions",
    "garlic",
    "ginger",
    "potatoes",
    "sweet potatoes",
    "beets",
    "corn",
    "green beans",
    "peas",
    "asparagus",
    "brussels sprouts",
    "artichokes",
    "beef",
    "chicken",
    "pork",
    "lamb",
    "bacon",
    "sausage",
    "ham",
    "turkey",
    "fish",
    "shrimp",
    "lobster",
    "crab",
    "clams",
    "mussels",
    "salmon",
    "tuna",
    "anchovies",
    "soy protein",
    "tofu",
    "tempeh",
    "seitan",
    "quorn",
    "eggs",
    "miso",
    "soba noodles",
    "rice noodles",
    "couscous",
    "tortillas",
    "dijon mustard",
    "whole grain mustard",
    "mayonnaise",
    "ketchup",
    "hot sauce",
    "barbecue sauce",
    "soy sauce",
    "fish sauce",
    "Worcestershire sauce",
    "hummus",
    "salsa",
    "guacamole",
    "pasta sauce",
    "tomato paste",
    "sriracha",
    "hoisin sauce",
    "peanut butter",
    "jam",
    "honey",
    "molasses",
    "chocolate",
    "vanilla extract",
    "cocoa powder",
    "gelatin",
    "corn syrup",
    "coconut flakes",
    "marshmallows",
    "sprinkles",
    "food coloring",
    "salt",
    "pepper",
    "paprika",
    "cumin",
    "coriander",
    "cayenne pepper",
    "chili powder",
    "garlic powder",
    "onion powder",
    "turmeric",
    "oregano",
    "thyme",
    "rosemary",
    "dill",
    "bay leaves",
    "cinnamon",
    "nutmeg",
    "cloves",
    "cardamom",
    "star anise",
    "tamarind",
    "mustard seeds",
    "cane sugar",
    "brown sugar",
    "powdered sugar",
    "confectioners' sugar",
    "granulated sugar",
    "molasses",
    "cornstarch",
    "potato starch",
    "arrowroot",
    "xanthan gum",
    "cream cheese",
    "sour cream",
    "yogurt",
    "buttermilk",
    "heavy cream",
    "whipping cream",
    "evaporated milk",
    "condensed milk",
    "cream of tartar",
    "lemon juice",
    "lime juice",
    "orange juice",
    "apple cider vinegar",
    "red wine vinegar",
    "balsamic vinegar"]
    return list(set(ingredients))
