def ingredients():
    ingredients = [
    "flour",
    "sugar",
    "butter",
    "eggs",
    "milk",
    "salt",
    "pepper",
    "vanilla extract",
    "baking powder",
    "baking soda",
    "chocolate chips",
    "cocoa powder",
    "honey",
    "maple syrup",
    "olive oil",
    "vegetable oil",
    "coconut oil",
    "soy sauce",
    "rice vinegar",
    "sesame oil",
    "garlic",
    "onion",
    "ginger",
    "cilantro",
    "parsley",
    "basil",
    "thyme",
    "rosemary",
    "oregano",
    "cumin",
    "coriander",
    "cayenne pepper",
    "paprika",
    "nutmeg",
    "cinnamon",
    "turmeric",
    "mustard seeds",
    "bay leaves",
    "cloves",
    "cardamom",
    "star anise",
    "tamarind",
    "black pepper",
    "white pepper",
    "red pepper flakes",
    "cane sugar",
    "brown sugar",
    "powdered sugar",
    "confectioners' sugar",
    "granulated sugar",
    "molasses",
    "cornstarch",
    "potato starch",
    "arrowroot",
    "xanthan gum",
    "cream cheese",
    "sour cream",
    "yogurt",
    "buttermilk",
    "heavy cream",
    "whipping cream",
    "evaporated milk",
    "condensed milk",
    "cream of tartar",
    "lemon juice",
    "lime juice",
    "orange juice",
    "apple cider vinegar",
    "red wine vinegar",
    "balsamic vinegar",
    "coconut milk",
    "almond milk",
    "cashew milk",
    "rice milk",
    "soy milk",
    "oats",
    "quinoa",
    "rice",
    "pasta",
    "barley",
    "bulgur",
    "couscous",
    "bread crumbs",
    "cornmeal",
    "walnuts",
    "almonds",
    "cashews",
    "peanuts",
    "hazelnuts",
    "pecans",
    "macadamia nuts",
    "pistachios",
    "sunflower seeds",
    "pumpkin seeds",
    "chia seeds",
    "flaxseeds",
    "poppy seeds",
    "sesame seeds",
    "dried cranberries",
    "raisins",
    "dates",
    "figs",
    "prunes",
    "apricots",
    "cherries",
    "blueberries",
    "strawberries",
    "raspberries",
    "blackberries",
    "bananas",
    "apples",
    "pears",
    "peaches",
    "plums",
    "kiwis",
    "mangoes",
    "pineapples",
    "avocados",
    "lemons",
    "limes",
    "oranges",
    "grapefruits",
    "watermelon",
    "cantaloupe",
    "honeydew melon",
    "coconut",
    "passion fruit",
    "dragon fruit",
    "pomegranate",
    "tomatoes",
    "cucumbers",
    "carrots",
    "celery",
    "bell peppers",
    "spinach",
    "kale",
    "lettuce",
    "arugula",
    "zucchini",
    "eggplant",
    "broccoli",
    "cauliflower",
    "mushrooms",
    "onions",
    "garlic",
    "ginger",
    "potatoes",
    "sweet potatoes",
    "beets",
    "corn",
    "green beans",
    "peas",
    "asparagus",
    "brussels sprouts",
    "artichokes",
    "beef",
    "chicken",
    "pork",
    "lamb",
    "bacon",
    "sausage",
    "ham",
    "turkey",
    "fish",
    "shrimp",
    "lobster",
    "crab",
    "clams",
    "mussels",
    "salmon",
    "tuna",
    "anchovies",
    "soy protein",
    "tofu",
    "tempeh",
    "seitan",
    "quorn",
    "eggs",
    "miso",
    "soba noodles",
    "rice noodles",
    "couscous",
    "tortillas",
    "dijon mustard",
    "whole grain mustard",
    "mayonnaise",
    "ketchup",
    "hot sauce",
    "barbecue sauce",
    "soy sauce",
    "fish sauce",
    "Worcestershire sauce",
    "hummus",
    "salsa",
    "guacamole",
    "pasta sauce",
    "tomato paste",
    "sriracha",
    "hoisin sauce",
    "peanut butter",
    "jam",
    "honey",
    "molasses",
    "chocolate",
    "vanilla extract",
    "cocoa powder",
    "gelatin",
    "corn syrup",
    "coconut flakes",
    "marshmallows",
    "sprinkles",
    "food coloring",
    "salt",
    "pepper",
    "paprika",
    "cumin",
    "coriander",
    "cayenne pepper",
    "chili powder",
    "garlic powder",
    "onion powder",
    "turmeric",
    "oregano",
    "thyme",
    "rosemary",
    "dill",
    "bay leaves",
    "cinnamon",
    "nutmeg",
    "cloves",
    "cardamom",
    "star anise",
    "tamarind",
    "mustard seeds",
    "cane sugar",
    "brown sugar",
    "powdered sugar",
    "confectioners' sugar",
    "granulated sugar",
    "molasses",
    "cornstarch",
    "potato starch",
    "arrowroot",
    "xanthan gum",
    "cream cheese",
    "sour cream",
    "yogurt",
    "buttermilk",
    "heavy cream",
    "whipping cream",
    "evaporated milk",
    "condensed milk",
    "cream of tartar",
    "lemon juice",
    "lime juice",
    "orange juice",
    "apple cider vinegar",
    "red wine vinegar",
    "balsamic vinegar"]
    return list(set(ingredients))

def recipes():
    recipe_list = [
        "Classic Chocolate Chip Cookies",
        "Spaghetti Bolognese",
        "Roast Chicken with Garlic and Herbs",
        "Cheeseburger",
        "Caesar Salad",
        "Homemade Pizza",
        "Pancakes with Maple Syrup",
        "Grilled Cheese Sandwich",
        "Chicken Noodle Soup",
        "Chocolate Brownies",
        "Guacamole",
        "Vanilla Ice Cream",
        "Hamburger",
        "Mashed Potatoes",
        "Tiramisu",
        "French Toast",
        "Chicken Parmesan",
        "Apple Pie",
        "Caprese Salad",
        "Beef Stew",
        "Blueberry Muffins",
        "Fish and Chips",
        "Pasta Carbonara",
        "Crispy Fried Chicken",
        "Chocolate Cake",
        "Omelette",
        "Chicken Fried Rice",
        "Strawberry Shortcake",
        "Eggs Benedict",
        "Garden Salad",
        "Meatloaf",
        "Key Lime Pie",
        "Cinnamon Rolls",
        "BBQ Ribs",
        "Shrimp Scampi",
        "Potato Salad",
        "Pumpkin Soup",
        "Lemon Bars",
        "Tomato Soup",
        "Cobb Salad",
        "Beef Tacos",
        "Apple Crisp",
        "Baked Ziti",
        "Cheesecake",
        "Spinach and Feta Stuffed Chicken",
        "Banana Bread",
        "Chicken Quesadillas",
        "Spicy Thai Peanut Noodles",
        "Honey Sriracha Glazed Salmon",
        "Balsamic Glazed Brussels Sprouts",
        "Curry Cauliflower Steaks",
        "Sesame Ginger Tofu Stir-Fry",
        "Mexican Street Corn Salad",
        "Mediterranean Quinoa Salad",
        "Garlic Butter Shrimp Skewers",
        "Teriyaki Pineapple Chicken",
        "Cajun Stuffed Bell Peppers",
        "Pesto Zucchini Noodles",
        "Black Bean and Sweet Potato Enchiladas",
        "Quinoa Stuffed Portobello Mushrooms",
        "Coconut Curry Lentil Soup",
        "Baked Buffalo Cauliflower Bites",
        "Caprese Stuffed Avocado",
        "Thai Green Curry",
        "Lemon Garlic Butter Salmon",
        "Mexican Quinoa Stuffed Peppers",
        "Mango Salsa Chicken",
        "Creamy Garlic Parmesan Brussels Sprouts",
        "Teriyaki Tofu Bowl",
        "Greek Lemon Chicken Soup",
        "Spinach Artichoke Stuffed Mushrooms",
        "Roasted Butternut Squash Soup",
        "Cilantro Lime Grilled Shrimp",
        "Italian Stuffed Bell Peppers",
        "Honey Mustard Glazed Pork Chops",
        "Vegan Lentil Chili",
        "Roasted Red Pepper Pasta",
        "Lemon Herb Grilled Chicken",
        "Curried Cauliflower Soup",
        "Crispy Baked Eggplant Fries",
        "Mushroom and Goat Cheese Tart",
        "Southwest Quinoa Salad",
        "Garlic Butter Steak Bites",
        "Sweet Potato Black Bean Burgers",
        "Sesame Ginger Beef Stir-Fry",
        "Baked Zucchini Parmesan Crisps",
        "Thai Coconut Curry Noodle Soup",
        "Cajun Shrimp and Sausage Skillet",
        "Greek Orzo Salad",
        "Peanut Butter Banana Protein Smoothie",
        "Honey Garlic Glazed Salmon",
        "Roasted Vegetable Quinoa",
        "Creamy Garlic Parmesan Pasta",
        "Mediterranean Baked Cod",
        "Cauliflower Fried Rice",
        "Caprese Quinoa Stuffed Tomatoes",
        "Chickpea Spinach Stew",
        "Crispy Baked Tofu",
        "Roasted Garlic Cauliflower Chowder",
        "Carbonara Zucchini Noodles"]
    return list(set(recipe_list))